---
Administrator:
  authentication:
    type: nick
    nick: jsvana
  class: Administrator
Alfred:
  class: Alfred
  respond_to_private_messages: true
Scorekeeper:
  class: Scorekeeper
Insulter:
  class: Insulter
